name: lint

on: [push, pull_request]

env:
  WESNOTH_VERSION: 1.16.10

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: add-ons
    - name: Lint WML
      uses: czyzby/wesnoth-wml-linter@v1
      with:
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
        spellcheck: false
    - name: Verify images
      uses: czyzby/wesnoth-png-optimizer@v1
      if: always()
      with:
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
        threshold: 11
